add haley
drakeapps/lunchaware.com pull request #16
Opened 2021-09-08 16:01 UTC by Brogdor

2021-09-08 16:06 UTC, drakeapps commented
Needs more dankness

2021-09-14 16:56 UTC, drakeapps requested changes

2021-09-14 16:56 UTC, drakeapps commented on index.php
> +  @for $i from 0 through 100 {
Cool sass, but we don't do that round these parts

2021-12-17 04:09 UTC, closed without merging

2021-12-17 04:18 UTC, thornjad commented
Brutal